const images = {
  Logo: require('./images/image 5.png'),
  Logo_Footer: require('./images/Logo_F.png'),
  Logo_Cilil: require('./images/logo-cicil-white 1.png'),
  Logo_BNI: require('./images/image 25.png'),
  Logo_PermataBank: require('./images/image 26.png'),
  Logo_MC: require('./images/image 27.png'),
  Logo_Danamon: require('./images/image 28.png'),
  Logo_VISA: require('./images/image 29.png'),
  Logo_mandiri: require('./images/image 32.png'),
  Logo_Kredivo: require('./images/image 33.png'),
  Logo_UOB: require('./images/image 34.png'),
  Logo_GOPAY: require('./images/image 35.png'),
  Logo_SC: require('./images/image 36.png'),

  Logo_BNI_light: require('./images/image 46.png'),
  Logo_PermataBank_light: require('./images/image 45.png'),
  Logo_MC_light: require('./images/image 44.png'),
  Logo_Danamon_light: require('./images/image 43.png'),
  Logo_VISA_light: require('./images/image 37.png'),
  Logo_mandiri_light: require('./images/image 38.png'),
  Logo_Kredivo_light: require('./images/image 39.png'),
  Logo_UOB_light: require('./images/image UOB.png'),
  Logo_GOPAY_light: require('./images/image 41.png'),
  Logo_SC_light: require('./images/image 42.png'),


  Btn_Left: require('./images/Left.png'),
  Btn_Right: require('./images/Right.png'),
  Left_Arrow: require('./images/Left-Arrow.png'),
  Right_Arrow: require('./images/Right-Arrow.png'),

  Icon_Search: require('./images/search.png'),
  Icon_User: require('./images/user.png'),
  Icon_Cart: require('./images/cart.png'),
  Icon_Trash: require('./images/trash.png'),
  Icon_AddCart: require('./images/add-cart.png'),
  Icon_Fb: require('./images/Facebook.png'),
  Icon_Ig: require('./images/Instagram.png'),
  Icon_Tw: require('./images/Twitter.png'),
  Icon_Yt: require('./images/Youtube.png'),
  Icon_Plus: require('./images/Plus.png'),
  Icon_Minus: require('./images/Minus.png'),
  Icon_Model_1: require('./images/Model1.png'),
  Icon_Model_2: require('./images/Model2.png'),
  Icon_Checkout_On: require('./images/checkout.png'),
  Icon_Confirm_On: require('./images/confirm (2).png'),
  Icon_Payment_On: require('./images/payment (2).png'),
  Icon_Checkout_Off: require('./images/checkout (2).png'),
  Icon_Confirm_Off: require('./images/confirm.png'),
  Icon_Payment_Off: require('./images/payment.png'),
  Icon_Confirm: require('./images/undraw_completing_6bhr 1.png'),

  Vector_1: require('./images/Vector1.png'),
  Vector_2: require('./images/Vector2.png'),
  Vector_3: require('./images/Vector3.png'),
  Vector_4: require('./images/Vector 15.png'),
  Vector_5: require('./images/Vector 16.png'),
  Vector_6: require('./images/Vector 17.png'),
  Vector_7: require('./images/Vector 19.png'),


  Product_1: require('./images/image 6.png'),
  Product_2: require('./images/image 10.png'),
  Product_3: require('./images/image 11.png'),
  Product_4: require('./images/image 12.png'),
  Product_5: require('./images/image 13.png'),
  Product_6: require('./images/image 15.png'),
  Product_7: require('./images/image 7.png'),
  Product_8: require('./images/image 8.png'),
  Product_9: require('./images/image 18.png'),
  Product_10: require('./images/image 19.png'),
  Product_11: require('./images/image 20.png'),
  Product_12: require('./images/image 21.png'),
  Product_13: require('./images/image 22.png'),
  Product_14: require('./images/image 23.png'),
  Product_17: require('./images/image 24.png'),
  Product_15: require('./images/image 8.png'),
  Product_16: require('./images/image 9.png'),
  Product_18: require('./images/image 17.png'),

  Product_1_Review_1: require('./images/image-removebg-preview 1.png'),
  Product_1_Review_2: require('./images/image-removebg-preview1 1.png'),
  Product_1_Review_3: require('./images/image-removebg-preview2 1.png'),

  Describe: require('./images/image 40.png'),

  Social_1: require('./images/Rectangle 38.png'),
  Social_2: require('./images/Rectangle 39.png'),
  Social_3: require('./images/Rectangle 40.png'),
  Social_4: require('./images/Rectangle 41.png'),
  Social_5: require('./images/Rectangle 42.png'),
}

export default images;