import { dataProducts } from '../../../../common/data';
import images from '../../../../assets/Images';

export const listProduct: dataProducts[] = [
  {
    id: 0,
    img: images.Product_4,
    name: "Way Kambas Maple",
    discount: 20,
    price: 1500000,
    promotion: 1264000,
    series: "Ebony Series",
    tag: "",
  },
  {
    id: 1,
    img: images.Product_11,
    name: "Singo Ebony",
    discount: 20,
    price: 1500000,
    promotion: 1264000,
    series: "Maple Series",
    tag: "",
  },
  {
    id: 2,
    img: images.Product_6,
    name: "Rakai Ebony",
    discount: 15,
    price: 1280000,
    promotion: 1118000,
    series: "Featured",
    tag: "",
  },
  {
    id: 3,
    img: images.Product_12,
    name: "Way Kambas Mini Maple",
    discount: 10,
    price: 1280000,
    promotion: 1024000,
    series: "Featured",
    tag: "",
  },
  {
    id: 4,
    img: images.Product_11,
    name: "Singo Ebony",
    discount: 20,
    price: 1500000,
    promotion: 1264000,
    series: "Maple Series",
    tag: "",
  },
  {
    id: 5,
    img: images.Product_11,
    name: "Singo Ebony",
    discount: 20,
    price: 1500000,
    promotion: 1264000,
    series: "Maple Series",
    tag: "",
  },
  {
    id: 6,
    img: images.Product_11,
    name: "Singo Ebony",
    discount: 20,
    price: 1500000,
    promotion: 1264000,
    series: "Ebony Series",
    tag: "",
  },
  {
    id: 7,
    img: images.Product_11,
    name: "Singo Ebony",
    discount: 20,
    price: 1500000,
    promotion: 1264000,
    series: "Ebony Series",
    tag: "",
  },
  {
    id: 8,
    img: images.Product_11,
    name: "Singo Ebony",
    discount: 20,
    price: 1500000,
    promotion: 1264000,
    series: "Featured",
    tag: "",
  },
];
